process.env.APP_ENV = 'test';
process.env.DATABASE_URL =
  'postgresql://mucyora_auth_app:placeholder@localhost:5432/mucyora';
process.env.IDENTITY_ENCRYPTION_KEY_VERSION = 'v1';
process.env.IDENTITY_ENCRYPTION_SECRET =
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';
process.env.IDENTITY_LOOKUP_KEY_VERSION = 'v1';
process.env.IDENTITY_LOOKUP_HMAC_KEY =
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE';
process.env.TOKEN_DIGEST_HMAC_KEY =
  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI';
process.env.REQUEST_CONTEXT_HMAC_KEY =
  'AwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM';
